created coach card and updated classes page
jimmybatuhan/riival pull request #22
Opened 2020-11-19 03:36 UTC by dryldionisio

2020-11-27 11:50 UTC, jimmybatuhan requested changes
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/22)* status: 0 of 3 files reviewed, 26 unresolved discussions (waiting on @dryldionisio and @jimmybatuhan)

___
*[resources/js/components/CoachCard.vue, line 8 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WF139-WHCRxpXvEC:-MN8WF14DMiyu_TpNvKy:bwbux4c) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L8)):*
> ```Vue
>         </div>
>         <div class="card-body px-3 pt-1">
>             <div class="container mt-3">
> ```

indent properly
___
*[resources/js/components/CoachCard.vue, line 17 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WHgh7yCJksUOm8K5:-MN8WHgh7yCJksUOm8K6:bwbux4c) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L17)):*
> ```Vue
>                 </div>
>             </div>
>         </div>
> ```

indent properly
___
*[resources/js/components/CoachCard.vue, line 23 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WLyf8LWtwCowV5md:-MN8WLyf8LWtwCowV5me:b-6kb57j) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L23)):*
> ```
> coach-box{
> ```
space before bracket
___
*[resources/js/components/CoachCard.vue, line 29 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WQDY86EbEKe2VgiX:-MN8WQDY86EbEKe2VgiY:bkz3unx) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L29)):*
> ```
> .coach-box >.card-heade
> ```
`> .card-header`
___
*[resources/js/components/CoachCard.vue, line 51 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WWWM1Biz-4B2ZphU:-MN8WWWM1Biz-4B2ZphV:bvl9dfb) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L51)):*
> ```
> .coach-box > .card-body{
> ```
same
___
*[resources/js/components/CoachCard.vue, line 56 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WY3R3fbjdAcowUbR:-MN8WY3R3fbjdAcowUbS:bym2o8v) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L56)):*
> ```
> .coach-button-box{
> ```
same
___
*[resources/js/components/CoachCard.vue, line 70 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WZWyEQWkERqOCrnE:-MN8WZWyEQWkERqOCrnF:b-nby7z8) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L70)):*
> ```
>  default: "teaches dota 2"
> ```
no need, if required
___
*[resources/js/components/CoachCard.vue, line 76 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WatX1pYyL-c-pIlL:-MN8WatX1pYyL-c-pIlM:b9zqqkz) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L76)):*
> ```
>  default: "NOTAIL"
> ```
same
___
*[resources/js/components/CoachCard.vue, line 82 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wc7E6TSqLB9oilLy:-MN8Wc7E6TSqLB9oilLz:b-gubfak) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L82)):*
> ```
>  default: "/img/coach@2x.png"
> ```
same
___
*[resources/js/components/CoachCard.vue, line 88 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WdCH8RtCZC4wShGg:-MN8WdCH8RtCZC4wShGh:b-o4lg5t) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L88)):*
> ```
>   default: "#"
> ```
same
___
*[resources/js/components/CoachCard.vue, line 89 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wdrw-bYNvccexiPX:-MN8Wdrw-bYNvccexiPY:b3kqv) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L89)):*
> ```Vue
>             required: true,
>             default: "#"
>         }
> ```

,
___
*[resources/js/components/CoachCard.vue, line 90 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WeU46KKMAWV1rKQf:-MN8WeU46KKMAWV1rKQg:b3kqv) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L90)):*
> ```Vue
>             default: "#"
>         }
>     }
> ```

,
___
*[resources/js/components/CoachCard.vue, line 92 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wf1I2Y3xdbLxp0sg:-MN8Wf1I2Y3xdbLxp0sh:b2ni21j) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L92)):*
> ```Vue
>     }
> }
> </script>
> ```

eof
___
*[resources/js/modules/Classes.vue, line 12 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WjoO3tjmONj0ojJ1:-MN8WjoO3tjmONj0ojJ2:beyry47) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L12)):*
> ```
> alt=""
> ```
remove if empty
___
*[resources/js/modules/Classes.vue, line 18 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wnj93fwumeaxTlpk:-MN8Wnj93fwumeaxTlpl:b46y15z) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L18)):*
> ```
> ······
> ```
remove
___
*[resources/js/modules/Classes.vue, line 25 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WozD9Rx7ML8yxZm7:-MN8WozD9Rx7ML8yxZm8:be1b1on) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L25)):*
> ```
> ········
> ```
remove
___
*[resources/js/modules/Classes.vue, line 117 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WuFFC3cU_V2MLzd1:-MN8WuFFC3cU_V2MLzd2:b-g88xyx) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L117)):*
> ```
> ············
> ```
remove
___
*[resources/js/modules/Classes.vue, line 123 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8XBGB7PYS0Xo4WURB:-MN8XBGB7PYS0Xo4WURC:btpfe4e) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L123)):*
> ```
> .coach-box{
> ```
same
___
*[resources/js/modules/Classes.vue, line 129 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WwxC6BXsnecW6S-P:-MN8WwxC6BXsnecW6S-Q:bifdhn) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L129)):*
> ```
> .coach-box >.card-header
> ```
` .coach-box > .card-header`
___
*[resources/js/modules/Classes.vue, line 138 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8X5vy4qqPPrU0cPl1:-MN8X5vy4qqPPrU0cPl2:b-993za) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L138)):*
> ```
> .input-group-text{
> ```
same
___
*[resources/js/modules/Classes.vue, line 139 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8X76V14Y8opWqP0DB:-MN8X76V14Y8opWqP0DC:b-t3qqio) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L139)):*
> ```
>  .input-group-text{
> ```
same
___
*[resources/js/modules/Classes.vue, line 144 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8X8836DPPWfLpAEl3:-MN8X8836DPPWfLpAEl4:b-b87rap) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L144)):*
> ```
>  .search-hr{
> ```
same
___
*[resources/js/m [...]

2020-11-30 02:14 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 8 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WF139-WHCRxpXvEC:-MNLvZM9Cob_H20WiEo-:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L8)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

indent properly
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:14 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 17 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WHgh7yCJksUOm8K5:-MNLvaTQ9gJuyUyWrnra:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L17)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

indent properly
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:15 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 23 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WLyf8LWtwCowV5md:-MNLvcmOB9O3Sy5uT5Id:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L23)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> coach-box{
> ```
space before bracket
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:15 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 29 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WQDY86EbEKe2VgiX:-MNLvfWc9DsQaDUijPL9:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L29)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> .coach-box >.card-heade
> ```
`> .card-header`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:15 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 51 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WWWM1Biz-4B2ZphU:-MNLvi0P71WMtKot47ST:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L51)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> .coach-box > .card-body{
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:15 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 56 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WY3R3fbjdAcowUbR:-MNLvj2p0c-IY4DHS7nd:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L56)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> .coach-button-box{
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:15 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 70 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WZWyEQWkERqOCrnE:-MNLvkN76hIYlTQatWT_:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L70)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  default: "teaches dota 2"
> ```
no need, if required
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:15 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 76 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WatX1pYyL-c-pIlL:-MNLvlLOBsvw0Gq69Vo4:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L76)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  default: "NOTAIL"
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:15 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 82 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wc7E6TSqLB9oilLy:-MNLvmG-5mYx-a_cCVPG:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L82)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  default: "/img/coach@2x.png"
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:15 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 89 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wdrw-bYNvccexiPX:-MNLvobWBdBfSi4NoM9_:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L89)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

,
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:15 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 90 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WeU46KKMAWV1rKQf:-MNLvpQ57lg0zYcZFayV:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L90)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

,
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 92 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wf1I2Y3xdbLxp0sg:-MNLvqU2DTnnQST5wjKT:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L92)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

eof
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 12 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WjoO3tjmONj0ojJ1:-MNLvt1n32IbTPcmcesm:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L12)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> alt=""
> ```
remove if empty
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 18 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wnj93fwumeaxTlpk:-MNLvuUzEQjpt4ihWc7Q:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L18)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> ······
> ```
remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 25 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WozD9Rx7ML8yxZm7:-MNLvwF-8CEyXlLEV4ui:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L25)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> ········
> ```
remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 117 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WuFFC3cU_V2MLzd1:-MNLvxQIBDqm4XNQPILw:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L117)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> ············
> ```
remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 123 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8XBGB7PYS0Xo4WURB:-MNLvz83DMnkXpBaAySf:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L123)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> .coach-box{
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 129 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WwxC6BXsnecW6S-P:-MNLw-hB4SJ5U8YH04FS:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L129)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> .coach-box >.card-header
> ```
` .coach-box > .card-header`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 138 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8X5vy4qqPPrU0cPl1:-MNLw0ZO1ZysiP4Nz4gt:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L138)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> .input-group-text{
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 139 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8X76V14Y8opWqP0DB:-MNLw1Qu6vxA9hzLdNtK:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L139)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  .input-group-text{
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 144 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8X8836DPPWfLpAEl3:-MNLw2Bw1jw_CKPa0oYR:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L144)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  .search-hr{
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:16 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 149 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8X9XA3BGttmlMtw0h:-MNLw3C2C7VxJTrb-0SU:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L149)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  #search-input{
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:17 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 161 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8XF8A-YhtLxuZn9Vs:-MNLw4Vy30soCqCpXZBf:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L161)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove indention
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:17 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 166 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8XJ9G9IUR9aKMcEZB:-MNLw5i2-s9KrNFNxKkd:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L166)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>         created() {
>         },
> ```
remove if empty
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 02:17 UTC, dryldionisio commented
___
*[resources/js/modules/Classes.vue, line 177 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8XOHC48uuU2BRHdpO:-MNLw7Su4pU7ZTNIou6M:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/modules/Classes.vue#L177)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> <style>
> </style>
> ```
remove and add eof
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 13:37 UTC, jimmybatuhan requested changes
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/22)* status: 0 of 3 files reviewed, 23 unresolved discussions (waiting on @dryldionisio and @jimmybatuhan)

___
*[resources/js/components/CoachCard.vue, line 23 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WLyf8LWtwCowV5md:-MNOMb8p2PWcV4MGZt9r:b-hndcxy) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L23)):*
<details><summary><i>Previously, dryldionisio wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not donen
___
*[resources/js/components/CoachCard.vue, line 29 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WQDY86EbEKe2VgiX:-MNOMhix0zSG-Odgwru-:b-9qg1u4) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L29)):*
<details><summary><i>Previously, dryldionisio wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[resources/js/components/CoachCard.vue, line 56 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WY3R3fbjdAcowUbR:-MNOMkNc2Us0RzkVJBDg:b-9qg1u4) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L56)):*
<details><summary><i>Previously, dryldionisio wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[resources/js/components/CoachCard.vue, line 70 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WZWyEQWkERqOCrnE:-MNOMlTZ5e1zDZ3TPj6_:b-9qg1u4) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L70)):*
<details><summary><i>Previously, dryldionisio wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[resources/js/components/CoachCard.vue, line 76 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WatX1pYyL-c-pIlL:-MNOMmDE9JTORVicx1F9:b-9qg1u4) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L76)):*
<details><summary><i>Previously, dryldionisio wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[resources/js/components/CoachCard.vue, line 82 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wc7E6TSqLB9oilLy:-MNOMnkG9nVeO7UsFwY0:b-9qg1u4) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L82)):*
<details><summary><i>Previously, dryldionisio wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[resources/js/components/CoachCard.vue, line 88 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WdCH8RtCZC4wShGg:-MNOMoOcA0rBGoD_v-ui:b-9qg1u4) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L88)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>   default: "#"
> ```
same
</blockquote></details>

not done
___
*[resources/js/components/CoachCard.vue, line 90 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WeU46KKMAWV1rKQf:-MNOMpSnACO3W1-k7syU:b-9qg1u4) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L90)):*
<details><summary><i>Previously, dryldionisio wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[resources/js/components/CoachCard.vue, line 92 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8Wf1I2Y3xdbLxp0sg:-MNOMqtz9wzq-OBDYn9l:b-9qg1u4) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L92)):*
<details><summary><i>Previously, dryldionisio wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done


<!-- Sent from Reviewable.io -->

2020-12-03 08:58 UTC, jimmybatuhan requested changes
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/22)* status: all files reviewed, 2 unresolved discussions (waiting on @dryldionisio)

___
*[resources/js/components/CoachCard.vue, line 74 at r2](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MNboZEF2M1u93XE_ARE:-MNboZEF2M1u93XE_ARF:b3kqv) ([raw file](https://github.com/jimmybatuhan/riival/blob/17d437597d5ea62c51e0e068771883dd5243e7bc/resources/js/components/CoachCard.vue#L74)):*
> ```Vue
>             type: String,
>             required: true,
>         }
> ```

,
___
*[resources/js/components/CoachCard.vue, line 75 at r2](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MNbobEm24Jtb24OyFEn:-MNbobEm24Jtb24OyFEo:b3kqv) ([raw file](https://github.com/jimmybatuhan/riival/blob/17d437597d5ea62c51e0e068771883dd5243e7bc/resources/js/components/CoachCard.vue#L75)):*
> ```Vue
>             required: true,
>         }
>     }
> ```

,


<!-- Sent from Reviewable.io -->

2020-12-03 08:59 UTC, jimmybatuhan requested changes
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/22)* status: all files reviewed, 2 unresolved discussions (waiting on @dryldionisio)

___
*[resources/js/components/CoachCard.vue, line 74 at r2](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MNbor-E1OF9WdFMG6JU:-MNbor-E1OF9WdFMG6JV:b3kqv) ([raw file](https://github.com/jimmybatuhan/riival/blob/17d437597d5ea62c51e0e068771883dd5243e7bc/resources/js/components/CoachCard.vue#L74)):*
> ```Vue
>             type: String,
>             required: true,
>         }
> ```

,
___
*[resources/js/components/CoachCard.vue, line 75 at r2](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MNbosAy4Q3FYIGit9Xn:-MNbosAy4Q3FYIGit9Xo:b3kqv) ([raw file](https://github.com/jimmybatuhan/riival/blob/17d437597d5ea62c51e0e068771883dd5243e7bc/resources/js/components/CoachCard.vue#L75)):*
> ```Vue
>             required: true,
>         }
>     }
> ```

,


<!-- Sent from Reviewable.io -->

2020-12-03 08:59 UTC, jimmybatuhan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/22#-:-MNbou8N0712mCLh5Ada:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dryldionisio)



<!-- Sent from Reviewable.io -->

2020-12-03 09:14 UTC, dryldionisio reviewed
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/22)* status: all files reviewed, 2 unresolved discussions (waiting on @dryldionisio)

___
*[resources/js/components/CoachCard.vue, line 88 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MN8WdCH8RtCZC4wShGg:-MNLvnXh0KNCQK572sMn:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/39e402c97fee68324e84dcf6be2295d8d8923cbe/resources/js/components/CoachCard.vue#L88)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>   default: "#"
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 09:15 UTC, dryldionisio commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2020-12-03 09:16 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 74 at r2](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MNbor-E1OF9WdFMG6JU:-MNbsv1l6NuOVwzdmb9V:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/17d437597d5ea62c51e0e068771883dd5243e7bc/resources/js/components/CoachCard.vue#L74)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

,
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 09:17 UTC, dryldionisio commented
___
*[resources/js/components/CoachCard.vue, line 75 at r2](https://reviewable.io/reviews/jimmybatuhan/riival/22#-MNbosAy4Q3FYIGit9Xn:-MNbszDODP2KG7iZLfaH:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/17d437597d5ea62c51e0e068771883dd5243e7bc/resources/js/components/CoachCard.vue#L75)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

,
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 12:26 UTC, jimmybatuhan reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/22#-:-MNcZLJ8Br071H_Y59D5:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @jimmybatuhan)



<!-- Sent from Reviewable.io -->

2020-12-03 12:26 UTC, jimmybatuhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/22)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-03 12:27 UTC, dryldionisio commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2020-12-03 12:55 UTC, merged