added account info card for account settings
jimmybatuhan/riival pull request #23
Opened 2020-11-20 03:43 UTC by dryldionisio

2020-11-27 11:40 UTC, jimmybatuhan requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/23)* status: 1 of 2 files reviewed, 33 unresolved discussions (waiting on @dryldionisio and @jimmybatuhan)

___
*[resources/js/components/AccountInformation.vue, line 2 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UDJ44t6PopazbiOO:-MN8UDJ44t6PopazbiOP:b-l6mwxj) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L2)):*
> ```Vue
> <template>
>     
> ```

remove
___
*[resources/js/components/AccountInformation.vue, line 5 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UCQG0qFUfuqTbgdv:-MN8UCQG0qFUfuqTbgdw:b-g88xyx) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L5)):*
> ```
> ············
> ```
remove
___
*[resources/js/components/AccountInformation.vue, line 10 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8T2Kz2re1wKGL7rr5:-MN8T2L-DISK83tJhAL5:b-q8vvfd) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L10)):*
> ```
> CLASS
> ```
class
___
*[resources/js/components/AccountInformation.vue, line 15 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U7643d8QDryKDlD4:-MN8U7643d8QDryKDlD5:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L15)):*
> ```Vue
>                     <div class="row">
>                         <div class="col-12">
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 17 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UQ3M4JqNONVcLxLU:-MN8UQ3M4JqNONVcLxLV:b59y6n0) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L17)):*
> ```
> :value="fullName"
> ```
switch to v-model
___
*[resources/js/components/AccountInformation.vue, line 19 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U5bo0SEEDzK2FdTN:-MN8U5bo0SEEDzK2FdTO:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L19)):*
> ```Vue
>                                 <input type="text" class="form-control account-info-field" id="acct-info-full-name" placeholder="Full Name" :value="fullName">
>                             </div>
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 21 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8USL72ArWtv7adaFB:-MN8USL72ArWtv7adaFC:b-fghgpl) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L21)):*
> ```
> :value="email"
> ```
same
___
*[resources/js/components/AccountInformation.vue, line 23 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U7uw3XHNeTbEbaby:-MN8U7uw3XHNeTbEbabz:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L23)):*
> ```Vue
>                                 <input type="email" class="form-control account-info-field" id="acct-info-email" placeholder="Email Address" :value="email">
>                             </div>
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 27 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U8Xf0NZ4pDhtwBb7:-MN8U8Xf0NZ4pDhtwBb8:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L27)):*
> ```Vue
>                                 <input type="password" class="form-control account-info-field" id="acct-info-password" placeholder="New Password">
>                             </div>
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 31 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UG1d3s01lzGPGs8A:-MN8UG1d3s01lzGPGs8B:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L31)):*
> ```Vue
>                                 <input type="password" class="form-control account-info-field" id="acct-info-confirm-password" placeholder="Confirm Password">
>                             </div>
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 34 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UG_UAdh4IGjJaSTF:-MN8UG_UAdh4IGjJaSTG:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L34)):*
> ```Vue
>                         </div>
>                     </div>
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 36 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UH7E8Aeyn8rsC2_9:-MN8UH7E8Aeyn8rsC2_A:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L36)):*
> ```Vue
> 
>                 </div>
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 44 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UVn6A1VYtxCRfCS2:-MN8UVn6A1VYtxCRfCS3:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L44)):*
> ```Vue
>                     <h5 CLASS="font-weight-bold text-white ">BILLING INFORMATION</h5>
>                     <hr class="account-info-hr">
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 45 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8T8Wv46kUJzEX-CIH:-MN8T8Wv46kUJzEX-CII:bakzu6n) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L45)):*
> ```
> {{email}}
> ```
`{{ email }}`
___
*[resources/js/components/AccountInformation.vue, line 47 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8T6Hc1QZXZhVMv9OF:-MN8T6Hc1QZXZhVMv9OG:b5fxi1y) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L47)):*
> ```
> ················
> ```
remove spaces
___
*[resources/js/components/AccountInformation.vue, line 49 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UXhZAu7gsrOXdd7O:-MN8UXhZAu7gsrOXdd7P:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L49)):*
> ```Vue
>                 
>             </div>
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 55 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UYdq-EFtVYY7UWo5:-MN8UYdq-EFtVYY7UWo6:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L55)):*
> ```Vue
>                 </div>
>             </div>
> ```

remove empty line
___
*[resources/js/components/AccountInformation.vue, line 58 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8TC-WEiCEyWaF0YVt:-MN8TC-WEiCEyWaF0YVu:b-xexep1) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L58)):*
> ```
> href=""
> ```
remove
___
*[resources/js/components/AccountInformation.vue, line 61 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN [...]

2020-11-30 01:40 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 30 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MNLnj-_5iKoBmRhryhQ:-MNLnj-_5iKoBmRhryhR:bdiimbm) ([raw file](https://github.com/jimmybatuhan/riival/blob/edd63f1938373c185696f3432e21300a4d2864de/resources/js/components/AccountInformation.vue#L30)):*
> ```
>      <p class="text-white font-weight-bold">{{ email }}</p>
> ```


<!-- Sent from Reviewable.io -->

2020-11-30 01:42 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 2 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UDJ44t6PopazbiOO:-MNLo5fNA_c8fUGo7XoR:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L2)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:42 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 5 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UCQG0qFUfuqTbgdv:-MNLo9_b2hSvA05ZSnfT:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L5)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> ············
> ```
remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:42 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 10 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8T2Kz2re1wKGL7rr5:-MNLoCui8co-kMw3ev-2:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L10)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> CLASS
> ```
class
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:42 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 15 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U7643d8QDryKDlD4:-MNLoEuj8FuXG-M4X_2n:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L15)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:44 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 19 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U5bo0SEEDzK2FdTN:-MNLohQo8o-1MFsrrj4L:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L19)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:45 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 17 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UQ3M4JqNONVcLxLU:-MNLoIN_1jCMQocRM6_D:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L17)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> :value="fullName"
> ```
switch to v-model
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:46 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 21 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8USL72ArWtv7adaFB:-MNLp2Td5Spor5DtJDle:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L21)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> :value="email"
> ```
same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:46 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 23 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U7uw3XHNeTbEbaby:-MNLp4aq2G0116K7Gk3p:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L23)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:46 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 27 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U8Xf0NZ4pDhtwBb7:-MNLp5zu-11VdAPl0Vsy:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L27)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:46 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 31 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UG1d3s01lzGPGs8A:-MNLp6bpEpVD6QzfH-ez:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L31)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:46 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 34 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UG_UAdh4IGjJaSTF:-MNLp7M2EuSiiJhQEtTi:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L34)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:46 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 36 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UH7E8Aeyn8rsC2_9:-MNLp87H-9FAPH_Y3o7q:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L36)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:46 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 44 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UVn6A1VYtxCRfCS2:-MNLp9k7EwLOhXglmpoO:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L44)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:47 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 45 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8T8Wv46kUJzEX-CIH:-MNLpCT2CkOC0qCkMwAl:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L45)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> {{email}}
> ```
`{{ email }}`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:47 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 47 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8T6Hc1QZXZhVMv9OF:-MNLpDwM12OwD4Nfjgtl:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L47)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> ················
> ```
remove spaces
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:47 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 49 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UXhZAu7gsrOXdd7O:-MNLpEeFCUkPLRxSqQmH:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L49)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:47 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 55 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UYdq-EFtVYY7UWo5:-MNLpGD670eUbr2kSX4l:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L55)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:47 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 58 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8TC-WEiCEyWaF0YVt:-MNLpKDs8q6CEzrpAo4L:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L58)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> href=""
> ```
remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:47 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 61 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U_5n4R2Ze8T2CRBd:-MNLpLomApAe_SljIdBz:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L61)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:47 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 64 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8Ua8u5Nkn44MzfwKc:-MNLpNCvC5fNWjKLMEp_:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L64)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:47 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 68 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8TPZuC1g9OQHXve3y:-MNLpNpp7HcRoZKvfXoY:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L68)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:47 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 70 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UxIK47C5_z7C09bb:-MNLpQRR74q40ugZyBtj:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L70)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> .account-info-box>.card-body {
> ```
`.account-info-box > .card-body`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:48 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 76 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8UdTL6nDYSIWI47Zs:-MNLpSSt-Tf9rNxl88UB:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L76)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> .account-info-field{
> ```
space before opening bracket
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:48 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 83 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8Ugy4CD7P_jnnirwM:-MNLpVXV6j2oEjgEul17:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L83)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> .account-info-hr{
> ```
same apply to all
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:48 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 94 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8V2oLD4vrcqZdaGlG:-MNLpXvm4XksQzb5C6AL:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L94)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:48 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 106 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8U0xRDe7Sp8ZHOOG3:-MNLpZHI2ozLrKcY_SZo:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L106)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> default: "First Last"
> ```
if required, no need to set default value.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:48 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 112 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8TxDtEUQqOxz2ec2m:-MNLp_OAEa3KeBIybxbw:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L112)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> default: "firstlast@email.com"
> ```
if required, no need to set default value.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:48 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 114 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8V5NV4J0rLinM5i2M:-MNLpabw3DUrXyBePdgo:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L114)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 01:48 UTC, dryldionisio commented
___
*[resources/js/components/AccountInformation.vue, line 117 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MN8TVKM5cH08H3ju7Ty:-MNLpc66-O8J6vS68Rup:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/fca5f00305c9c433e146082c27cd7447787ec727/resources/js/components/AccountInformation.vue#L117)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

add new line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 08:54 UTC, jimmybatuhan requested changes
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/23)* status: all files reviewed, 2 unresolved discussions (waiting on @dryldionisio)

___
*[resources/js/modules/Settings.vue, line 46 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MNbniH57He8YBX1LoPG:-MNbniH69kOg_v2sXVcU:b-6p0oik) ([raw file](https://github.com/jimmybatuhan/riival/blob/edd63f1938373c185696f3432e21300a4d2864de/resources/js/modules/Settings.vue#L46)):*
> ```
> <style>
> </style>
> ```
remove


<!-- Sent from Reviewable.io -->

2020-12-03 08:59 UTC, jimmybatuhan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/23#-:-MNbozNW4PB5AOgOqy3v:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dryldionisio)



<!-- Sent from Reviewable.io -->

2020-12-03 12:23 UTC, dryldionisio commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2020-12-03 12:24 UTC, dryldionisio commented
___
*[resources/js/modules/Settings.vue, line 46 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/23#-MNbniH57He8YBX1LoPG:-MNcYxhnC9v3_UiDXxVX:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/edd63f1938373c185696f3432e21300a4d2864de/resources/js/modules/Settings.vue#L46)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> <style>
> </style>
> ```
remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 12:25 UTC, jimmybatuhan reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/23#-:-MNcZ7bk9PhjNKkTSvTI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jimmybatuhan)



<!-- Sent from Reviewable.io -->

2020-12-03 12:25 UTC, jimmybatuhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/23)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-03 12:49 UTC, merged